version: "3.8"

services:
  php:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
